# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "announcement-bar"
client_id = "d223836cb52dada0ea4cd7a8b3e77c1a"
application_url = "https://regions-military-counseling-favorite.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://regions-military-counseling-favorite.trycloudflare.com/auth/callback",
  "https://regions-military-counseling-favorite.trycloudflare.com/auth/shopify/callback",
  "https://regions-military-counseling-favorite.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "adelsa-dev-test.myshopify.com"
